dist: bionic

language: cpp

compiler:
  - gcc

before_script:
  # out-of-source build
  - mkdir build_tests
  - cd build_tests
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ..

script:
  - make
  # if the project uses ctest run the tests.
  - ctest -V

after_success:
  - make r_unit_tests_coverage
  - make rcom_unit_tests_coverage
